name: Docker CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: kubsu
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
        options: >-
          --health-cmd="pg_isready -U kubsu"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build TEST image (multi-stage)
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile
          target: test
          tags: kubsu-crud:test
          load: true

      - name: Run tests in container
        env:
          DATABASE_URL: postgresql+psycopg://kubsu:kubsu@localhost:5432/kubsu
        run: |
          docker run --rm --network host \
            -e DATABASE_URL="$DATABASE_URL" \
            kubsu-crud:test


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Login to Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Build & push runtime image
      - name: Build & Push runtime image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile
          target: runtime
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/kubsu-crud:latest

      # 3. IMPORTANT: HTTP HEALTHCHECK (замена SSH deploy)
      - name: Wait for remote deployment (HTTP check)
        run: |
          echo "Waiting for server to update image..."

          for i in {1..30}; do
            echo "Attempt $i..."

            code=$(curl -s -o /dev/null -w "%{http_code}" \
              http://212.192.134.135:60080/${{ secrets.USERNAME }}/users/ || true)

            echo "HTTP status: $code"

            if [ "$code" = "200" ] || [ "$code" = "301" ]; then
              echo "Service is UP"
              exit 0
            fi

            sleep 5
          done

          echo "Service did not become ready"
          exit 1
